// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUNLsJWLqskq8eJfcZB0KMPpgYL5yNSeU',
    appId: '1:205217031631:web:36fbe3e887e0bda4ed1eba',
    messagingSenderId: '205217031631',
    projectId: 'ecommerce-e9e0e',
    authDomain: 'ecommerce-e9e0e.firebaseapp.com',
    storageBucket: 'ecommerce-e9e0e.firebasestorage.app',
    measurementId: 'G-NM26C90N74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNRhGWAFKWpslj7IBY_aFQdDJxzEtfs-I',
    appId: '1:205217031631:android:f32fd78cfc2f3644ed1eba',
    messagingSenderId: '205217031631',
    projectId: 'ecommerce-e9e0e',
    storageBucket: 'ecommerce-e9e0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYUFLqgWU2cNgX29kvrnhdXYLpQLsXlpY',
    appId: '1:205217031631:ios:2d9c7ba1000adbcded1eba',
    messagingSenderId: '205217031631',
    projectId: 'ecommerce-e9e0e',
    storageBucket: 'ecommerce-e9e0e.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYUFLqgWU2cNgX29kvrnhdXYLpQLsXlpY',
    appId: '1:205217031631:ios:2d9c7ba1000adbcded1eba',
    messagingSenderId: '205217031631',
    projectId: 'ecommerce-e9e0e',
    storageBucket: 'ecommerce-e9e0e.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUNLsJWLqskq8eJfcZB0KMPpgYL5yNSeU',
    appId: '1:205217031631:web:0aa2071a1b04151eed1eba',
    messagingSenderId: '205217031631',
    projectId: 'ecommerce-e9e0e',
    authDomain: 'ecommerce-e9e0e.firebaseapp.com',
    storageBucket: 'ecommerce-e9e0e.firebasestorage.app',
    measurementId: 'G-30V8X4HQRL',
  );
}
